### ISSUE TITLE
Bass invalid musicxml generated due to staff-details.

### ISSUE THREAD

**Issue by amirmohamad-yu** [RafaelDolores/EECS2311_GROUP5_TAB_TO_MUSICXML#14]
# Description
When inputting the following bass tablature the software produces an incorrect setting of the step values for the staff-details, which leads to an invalid musicxml file.

# Reproduction
1. Launch application
2. Input the below sample bass tablature
3. Save to musicxml file
4. Render the file via an external software(In this case, [_soundSlice_](https://www.soundslice.com/musicxml-viewer/262e21b5466f42c88963f87df8fc5fc1/))
* sample input:
```
e|--1------------------|
B|-----------3--3------|
G|-----3---------2-----|
D|--------0----0-------|
```

* sample portion output xml from conversion:
  - The tuning step is set to 2, which is invalid. It should be the step tune of that string. The octave is also wrong along with issue #12 

Result |
-------|
```
           <staff-tuning line="4">
              <tuning-step>2</tuning-step>
              <tuning-octave>3</tuning-octave>
            </staff-tuning>
```

Expected |
---------|
```
           <staff-tuning line="4">
              <tuning-step>D</tuning-step>
              <tuning-octave>2</tuning-octave>
            </staff-tuning>
```
* output rendered via [_soundSlice_](https://www.soundslice.com/musicxml-viewer/262e21b5466f42c88963f87df8fc5fc1/)

Renders  | Cases  
------- | ------------------
![image](https://user-images.githubusercontent.com/77291875/112313207-fd18e580-8c7d-11eb-94ce-59a2fd6ccae1.png)| Result
The step should be correctly set and should not produce an invalid musixml file | Expected

# System/Details
Platform: Windows 10, Eclipse 2020-12 (4.18.0), OpenJDK 15.0.2
Version: master branch, commit 6028f70
Priority: High
Severity: High

**Comment by shawn-verma** [comment]
Thank you for your feedback, this has been fixed in develop, and the feature to customize staff tunings will be available in our next release.
