### ISSUE TITLE
won't interpret correct 3/4 time signature

### ISSUE THREAD

**Issue by MesaGonzalez-Miguel-216138323** [RafaelDolores/EECS2311_GROUP5_TAB_TO_MUSICXML#19]
### id
19

### Description
When given a guitar tab that should be in 3/4 time, it translates the tab but plays it in 4/4 time

### Who raised:
Miguel Mesa

### Title:
Program won't interpret 3/4 time signature 

### Platform:
Windows 10

### Reproduction
Given a text file with the intro to "Behind The Wall Of Sleep" by Black Sabbath (which should be in 3/4), after one hits convert, the preview shows the time signature as 4/4. When the file is saved and uploaded to a website that can interpret musicXML one can clearly see that the song is not playing in the intended time signature.

### Expected
A translation with the correct time signature was expected

### Actual
A translation with the wrong time signature was the actual result from the program.

### Priority:
medium

### Severity:
medium

### Screenshots
![image](https://user-images.githubusercontent.com/46364294/112408850-e65ea700-8cee-11eb-90de-d46acbd40f08.png)

**Comment by RafaelDolores** [comment]
Hi Miguel,
Thank you for pointing this out to us. Our application currently sets the time signature to 4/4 by default which is why it doesn't adjust it automatically. Our plan in the future is to provide a feature in the GUI that will allow the user to choose so.
