### ISSUE TITLE
Bug Report - User interface 

### ISSUE THREAD

**Issue by Obuya** [RafaelDolores/EECS2311_GROUP5_TAB_TO_MUSICXML#24]
#### Issue description

The file path and instrument of the previous tab are still displayed when no file is selected after hitting 'browse file'.  

#### Steps to reproduce the issue

1.  convert a valid tab. 
2. then select 'browse file' but don't select any file instead hit cancel.
3. select the convert button again. 

#### Expected result

- The file path and instrument fields should be empty. 

#### Actual result

- the previous file path and instrument is still displayed. 

https://user-images.githubusercontent.com/52579841/112414109-e3b47f80-8cf7-11eb-9924-0175494d3e00.mp4

**Comment by mohful** [comment]
Hello Obuya. Thank you for your bug report. We love to receive such reports as it helps us better our software design. 
This was a great catch, and i have fixed it. You should be able to see this fix in the next version of our software! Thank you once again!
